### ISSUE TITLE
add link to Xena spreadsheet?

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#1]
will upload TSV from source directly into Xena

**Comment by nathandunn** [comment]
just going to leave it in the backlog for now

**Comment by jingchunzhu** [comment]
https://github.com/ucscXena/ucsc-xena-client/blob/master/js/views/Column.js

**Comment by jingchunzhu** [comment]
[figure 5 pathway.pdf](https://github.com/ucscXena/XenaGoWidget/files/4156535/figure.5.pathway.pdf)

**Comment by nathandunn** [comment]
should look like what is in the pathways, but should be only for a binary set of data

**Comment by nathandunn** [comment]
Should be similar to the mupit links.

**Comment by nathandunn** [comment]
also similar to tumorMap

**Comment by jingchunzhu** [comment]
https://xenabrowser.net/?bookmark=c3856c5bed936475409f885560c23150

**Comment by nathandunn** [comment]
![image](https://user-images.githubusercontent.com/751274/73795493-9bd34180-475f-11ea-92e0-c70b413736aa.png)

**Comment by jingchunzhu** [comment]
https://xenabrowser.net/heatmap/?bookmark=6451afae2ee964475a2eb9c79d46900c
