### ISSUE TITLE
make cohort geneset distinction cleaner

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#111]
- [x] remove gap between cohorts to make distinction clearer
- [x] move labels to the edge if feasible (hide for 1)
- ~~fix hover on bottom one~~ #114 
- [x] look at improving speed
- [x] evaluate doing the same for geneset overview as well

- ~~~create a widget between the two XenaGoViewers that takes in this.state.apps for both sets of data~~
- ~~add one for geneset overview~~
- ~~add one for genes~~

**Comment by nathandunn** [comment]
like this: 


![Screen Shot 2018-08-29 at 10.56.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fa6b7191a379ef0c2e57415b4bbc21254d58eeb9cb74fce36f34985619e880390972903512a5bfd019bb50ba208a1ed7b4b98b4892fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e44b55ac15356ae070336e0a.png)

**Comment by nathandunn** [comment]
updated goal after discussion with @jingchunzhu

**Comment by jingchunzhu** [comment]
Looking at the mock above. The arrows (orange and green) will obscure the plot. If we want to bring users attention to these genes (significant geens), we should think of anyway.
