### ISSUE TITLE
LHS geneset overview widget should provide  (L/R) shading from cohort densities

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#112]
The geneset overview (when a geneset view is selected) should use shading from the cohort density from each geneset instead of shading based on the gene overlap between genesets. 

The left hand side of the object should be the top cohort and the right hand side should be the bottom cohort. 

from Conversation with @jingchunzhu

**Comment by nathandunn** [comment]
This is a bit tricky as we need to take the individual cohort data and have it calculate  independently each time for score density.

**Comment by nathandunn** [comment]
Probably the easiest thing would be to use a separate route for fetching and processing the cohort data once its been called and adjust the color that way.

**Comment by jingchunzhu** [comment]
are you referring to this?
![image](https://user-images.githubusercontent.com/999493/46437430-2e994180-c710-11e8-8832-c9151446093b.png)

Isn't the desired L/H shading is more or less this, except just one rectangle (not two)? 
![image](https://user-images.githubusercontent.com/999493/46437546-7cae4500-c710-11e8-99dc-6776f92fa31e.png)

**Comment by nathandunn** [comment]
@jingchunzhu  That is exactly right.     

We just need to redo that calculation when we have a selected gene as the data is currently unavailable (you have to recalculate for cohort filtering).
