### ISSUE TITLE
fixe some LH / RH shading

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#118]
- [x] provide a single method for all calls
    - [x] distinguish between single gene and multi-gene?
  

Algorithms should:

- [x] density = samples affected / # of samples / # of genes 
- [x] score = log(density)  + someMin > 0 and always 1 if pinned at some max (will have to play with this, but maybe we don't need this)
- [x] remove high score / normalization calculation

Seems very inconsistent and overall lighting. (TCGA Pancreatic vs TCGA Ovarian).  

I'm wondering if it is because it is ignoring SNV data.

- (3) modulation of nucleotide pools (not showing up at all)
- (15) cell cycle pancan
- (7) TGF-pancan - coloring is reversed

**Comment by nathandunn** [comment]
Somehow the incorrect data is being shown, as the scored data is set there properly.  Might be a mismatch of indices, or a subsequent push of data for a smaller set.     That, or the sort is completely missed.

The CNV data is definitely being pulled through and it is not dependent.  Need to run through and confirm data and types to make sure all is done correctly.

**Comment by nathandunn** [comment]
To sync, we will change the algorithms to a singular algorithm that:
- [ ] density = samples affected / # of samples / # of genes 
- [ ] score = log(density)  + someMin > 0 and always 1 if pinned at some max (will have to play with this, but maybe we don't need this)
- [ ] remove high score / normalization calculation

**Comment by nathandunn** [comment]
So, for a single gene, this should be able to approach linear.  

However, the larger issue is when we have multiple genes.

**Comment by jingchunzhu** [comment]
maybe you mean multiple lists. Either way, it is one score per half rectangle. All half rectangles should be on the same color scale, mean the same red means the same number.

**Comment by nathandunn** [comment]
Looking at  Poly(ADP-ribose) polymerase (PARP) and the Cohorts (1) TGCA Breast Cancer and (2) Cancer Cell Line Enc, we have in the header label respectively:

|type| cohort | affected | samples | genes | affected / samples / genes |
|-----|----|----|------|-----|------------|
|header | 1 | 143 | 963 | 3 | 0.04949809622706819|
|header | 2 | 3 | 53 | 3 |  0.018867924528301886 |
|overview | 1 | 18  | 963 | 3 | 0.006230529595015576 |
|overview| 2 |  2|  53 | 3 | 0.012578616352201257 |

So, the big problem is that what is counted seems to be getting dropped.

**Comment by nathandunn** [comment]
If I filter just for mutation I get:


|type| cohort | affected | samples | genes | affected / samples / genes |
|-----|----|----|------|-----|------------|
|header | 1 | 11 | 963 | 3 | 0.003807545863|
|header | 2 | 1 | 53 | 3 |  0.006289308176100628
|overview | 1 | 18  | 963 | 3 | 0.006230529595015576 |
|overview| 2 |  2|  53 | 3 | 0.012578616352201257 |

The overview is unchanged (thought it does not match).

**Comment by nathandunn** [comment]
Just for CNV i get:

|type| cohort | affected | samples | genes | affected / samples / genes |
|-----|----|----|------|-----|------------|
|header | 1 | 134 | 963 | 3 | 0.0463828 |
|header | 2 | 2 | 53 | 3 |  0.01257861635
|overview | 1 | 0  | 963 | 3 | 0 |
|overview| 2 |  0 |  53 | 3 | 0 |

**Comment by nathandunn** [comment]
Note that the numbers need not match up EXACTLY, since you can have a mutation and a CNV in the same sample and that would count as 1.  So, the sum should be greater or equal to the individual scores.

Obviously the missing CNV data (as I suspected), is the problem.

**Comment by nathandunn** [comment]
The bug is that the selectedCohort data should be a JSON object from https://raw.githubusercontent.com/ucscXena/cohortMetaData/master/defaultDataset.json instead of the name of the cohort.
