### ISSUE TITLE
L/H pathway font color: revert back to dynamic coloring

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/XenaGoWidget#130]
previous 
white over darker red shading
black over white to light red shading

current:
black over all shading

**Comment by nathandunn** [comment]
I think it was dynamic when there were two texts? 

I changed it a bit so its pretty clearly black even when there.

**Comment by nathandunn** [comment]
I think changing the color in the same body of text will be a bit jarring.  The other option is to put a consistent white box under the black text (or vexe versa), but I think this work swell.
