### ISSUE TITLE
verify Xena Pathway data sample details should be accurate

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#153]
At a minimum the top-level values are incorrect (they always seem to be done).

**Comment by nathandunn** [comment]
![Screen Shot 2018-11-28 at 1.26.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456fb6b7191a379f1102d4f5b575ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df248e54955a01b3665ee732431.png)

**Comment by nathandunn** [comment]
**Score on the LHS and RHS is:**

- https://github.com/ucscXena/XenaGoWidget/blob/develop/src/functions/ColorFunctions.js#L42 =   outputScore =   Math.log10(100 * inputScore  / ( numSamples * geneCount ) );

- inputScore =  firstDensity =   sum score of 1 per hit based on all genes 

- the individual view (assuming it is correct) ignores the number of genes, so they will always be out of step

**Comment by nathandunn** [comment]
![Screen Shot 2018-11-30 at 4.41.06 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226457f36b7191a37cf1162a4f5f595ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df248e74f51ad103564e2772431.png)

**Comment by nathandunn** [comment]
the data coming back definitely reflects what is shown and both sets have the full sample set  and the appropriate layout.  

If we compare this to the older data set , we can see . . .

**Comment by nathandunn** [comment]
![Screen Shot 2018-12-02 at 9.09.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216454f16b7191a371f112224f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a29941c95df248e94c56a316326ae7732431.png)

**Comment by nathandunn** [comment]
Looks like the data is a bit too dense here (for mismatch repair):

![Screen Shot 2018-12-02 at 9.12.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216454f16b7191a371f113294f5e595ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19041c95df248e94c56ad1b3666e0762431.png)

**Comment by nathandunn** [comment]
To recompare data . I think this looks correct, and reflects the gene data.  The drawing looks correct based on the data that is being provided, but the scores are WAY too dense:

![Screen Shot 2018-12-02 at 9.14.51 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216454f16b7191a371f1132f4f5a5e5ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df248e94c51a5173760e0732431.png)
![Screen Shot 2018-12-02 at 9.15.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216454f16b7191a371f1132e4f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19041c95df248e94c51a5173760e0722431.png)).

**Comment by nathandunn** [comment]
I fixed the min filter, but we can see that WAY too many things are colored incorrectly even though the samples look correct:

![Screen Shot 2018-12-02 at 9.29.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216454f16b7191a371f110224f5f565ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df248e94c50a4133e63e67e2431.png)

Looking at the data, though, it is properly drawing the Pathway data coming back, just the pathway data looks to be improperly filtered.

**Comment by nathandunn** [comment]
Looking at this again, I think that it looks the same as in previous ones, so maybe the best solution is to determine *WHICH* of these solutions is correct and why.

**Comment by nathandunn** [comment]
@jingchunzhu  I think maybe the thing to do would be to start evaluating what representations are correct for some of these smaller genesets (or create some fake ones) and sort of work backwards from there.

**Comment by jingchunzhu** [comment]
![image](https://user-images.githubusercontent.com/999493/49466856-ef41ac80-f7b5-11e8-8125-1e5ae352a386.png)

**Comment by jingchunzhu** [comment]
![image](https://user-images.githubusercontent.com/999493/49466893-fd8fc880-f7b5-11e8-9539-926398ac8b20.png)

**Comment by jingchunzhu** [comment]
I suspect that the pathway rows are sorted, which you do not need to sort them anymore
