### ISSUE TITLE
sample id in tooltip seems to be incorrect

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/XenaGoWidget#160]

**Comment by jingchunzhu** [comment]
The following six sample in tcga pancreatic cancer are affected in the gene MAPK7, shown in Xena. In the XenaGo app, there are also 6 samples, but the sample ids does not match
![image](https://user-images.githubusercontent.com/999493/49482125-b4a23900-f7e2-11e8-9bc8-4a12f811c9ea.png)

**Comment by nathandunn** [comment]
Dependent on #164 . . .

Would also be good to list if a sample is a hit or not as the tooltips are VERY small.
