### ISSUE TITLE
add gene to pathway search at top

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#164]
- [x] refix pathway highlight for a selected gene
- [ ] adjust the z-values so that the drop-down is OVER the pathway view

- [x] searching for a gene at the top should highlight both pathways and genes in viewer mode
- [x] selected gene remains in the box
- [x] fix styling so:
  - [x] integrate with material-ui? 
  - [x] background is white
  - [x] background is on the same line
- [x] searching for genes in pathway editor mode should highlight geneSets if possible
- [x] confirm that old search still works

**Comment by jingchunzhu** [comment]
100% agree. Also it will be even better if the gene is highlighted in the right side single geneset view if the gene is in the pathway.

**Comment by nathandunn** [comment]
note oon fixing the styling
