### ISSUE TITLE
number of samples affected in a pathway is not correct in the tooltip

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/XenaGoWidget#166]

**Comment by jingchunzhu** [comment]
the tooltip report there are 17 samples affected, python script independently find only 15 samples affect.

pathway: (8) Notch Signaling
cohort: TCGA Pancreatic Cancer

xena screenshot also show 15 samples affected:  http://dev.xenabrowser.net/heatmap/?bookmark=dded615b7a5c2cd1008d6392977d695f
![image](https://user-images.githubusercontent.com/999493/49829596-b0769e00-fd43-11e8-9574-f0176e130a9a.png)

**Comment by nathandunn** [comment]
@jingchunzhu  Could I get a list of the samples affected?  

I may need to provide something for the client as well. 

Thanks.

**Comment by nathandunn** [comment]
![Screen Shot 2018-12-13 at 2.07.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f06b7191a37af1122c4f5f585ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe64e5dac16366bee7e2431.png)

**Comment by nathandunn** [comment]
- 14 CN mutations + 1 somatic mutation from Xena directly (and validated by the python script)
- we are getting 17 "samples affected" for pancreatic + notch signaling



<img width="1186" alt="screen shot 2018-12-13 at 2 12 56 pm" src="https://user-images.githubusercontent.com/751274/49970788-498eeb80-fee1-11e8-9c7f-34f001c6f072.png">

**Comment by jingchunzhu** [comment]
code for calculating observed sample number is at https://github.com/jingchunzhu/wrangle/tree/master/xenaGo
in perSampleEventN.py in the function parse_perSampleEventInPathway and perSampleEventInPathway

**Comment by nathandunn** [comment]
The data comes from the wrong "affected" count, which is sumInstances(pathwayArray) code in PathwayScoresView

**Comment by nathandunn** [comment]
The `calculatePathwayDensity` function is working properly, but the associatedData piece is scoring too many columns.

**Comment by nathandunn** [comment]
Here are the mutation versus the copy number scores:

![Screen Shot 2018-12-17 at 3.11.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f46b7191a37bf1132a4f5e5e5ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19041c95df24ee1455da713356be0712431.png)

**Comment by nathandunn** [comment]
So, the Copy Number is correct, but the somatic mutations are scored way too high (10 instead of 1).  This is also curious as the display seems to be completely correct.

**Comment by nathandunn** [comment]
Its possible that within the somatic mutation piece, that the vector we are expecting is different.

**Comment by nathandunn** [comment]
So, running through this code, the first gene set from the mutation pipeline gets a total of 4 somatic mutations: 

https://github.com/ucscXena/XenaGoWidget/blob/develop/src/functions/DataFunctions.js#L87

and from here, 14 copy mutations.  However, there is a single overlap so we get a total of 17 samples affected:

https://github.com/ucscXena/XenaGoWidget/blob/develop/src/functions/DataFunctions.js#L99

Clearly the problem is the somatic mutations showing up when they should not and/or they show up incorrectly on a sample.   Visually, however, it shows up correctly. 

What I have right now is a bunch of samples with silent mutations showing up:

![image](https://user-images.githubusercontent.com/751274/50703406-d886b380-1008-11e9-835e-17596d76de91.png)

I'm wondering if the input has is setting the min differently, though, as I think the silent mutations shouldn't be showing up in the first place.

**Comment by nathandunn** [comment]
List of mutation samples for the Pancreatic samples are here:

```
sample data TCGA-IB-7651-01 119 Missense_Mutation 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Silent 1 0
5DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Missense_Mutation 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Silent 1 0
3DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Missense_Mutation 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Splice_Site 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Silent 1 0
DataFunctions.js:96 sample data TCGA-RB-A7B8-01 161 Silent 1 0
DataFunctions.js:96 sample data TCGA-FB-AAPP-01 55 Silent 1 0
2DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Silent 1 0
2DataFunctions.js:96 sample data TCGA-H6-8124-01 73 Silent 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Missense_Mutation 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Silent 1 0
5DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Missense_Mutation 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Silent 1 0
3DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Missense_Mutation 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Splice_Site 1 0
DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Silent 1 0
DataFunctions.js:96 sample data TCGA-RB-A7B8-01 161 Silent 1 0
DataFunctions.js:96 sample data TCGA-FB-AAPP-01 55 Silent 1 0
2DataFunctions.js:96 sample data TCGA-IB-7651-01 119 Silent 1 0
2DataFunctions.js:96 sample data TCGA-H6-8124-01 73 Silent 1 0
```

Filtered down is:

```
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-RB-A7B8-01
TCGA-FB-AAPP-01
TCGA-IB-7651-01
TCGA-H6-8124-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-IB-7651-01
TCGA-RB-A7B8-01
TCGA-FB-AAPP-01
TCGA-IB-7651-01
TCGA-H6-8124-01
```

resulting in:

```
TCGA-FB-AAPP-01
TCGA-H6-8124-01
TCGA-IB-7651-01
TCGA-RB-A7B8-01
```

**Comment by nathandunn** [comment]
The problem is that the proper min from the inputHash should be 2, not 0.    This is an easy fix now as we calculate pathway density for the global set with the wrong filter setting.
