### ISSUE TITLE
add documentation link

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#220]
add some supporting material on what the plots mean, and basic help page (for users) to help them to get some idea how to use the tool and what the tool tells them.

- [x] create documentation: major-documentation-fixes
  - [x] merge in PR
- [x] add link to top
- [x] evaluate documentations:
  - [x] gitbook
  - [x] rtd
  - [x] gatsbyjs
  - [x] wordpress

**Comment by nathandunn** [comment]
- also installation instructions

**Comment by maryjgoldman** [comment]
User-facing help is located here: https://ucsc-xena.gitbook.io/project/. I can make you an editor if you would like to see the .md files. Note the formatting is all provided by gitbook.

For dev-facing help, you'll have to talk to Brian to see what he would like.

**Comment by nathandunn** [comment]
@maryjgoldman  yes please.  

i think the dev-facing side is pretty easy for this single component, but @acthp  might have something more specific in mind

**Comment by maryjgoldman** [comment]
I just realized it will only let me have 2 members for free and Jing and I already am. Do you want to pick a page that looks the most relevant and I can send you a copy of the .md ?

**Comment by nathandunn** [comment]
Why don’t you pick a couple and point me to the realized doc and send the source as well.

Thanks,

Nathan

**Comment by maryjgoldman** [comment]
Here is the .md https://docs.google.com/document/d/1Q4AOw6zh-5bkMPKZp6gnjGnGIXqaNUn9qABI30voAyc/edit?usp=sharing

And the page: https://ucsc-xena.gitbook.io/project/how-do-i/how-do-i-make-subgroups

I took out the images since I have to load them manually into gitbook. So there's no point in putting them in a special directory or anything.

**Comment by nathandunn** [comment]
@maryjgoldman  After looking at this, I think it makes the most sense for me to edit the gitbook directly so that all of the documentation is in one place and then you can integrate it when its ready. 

Maybe the easiest is if you 1) make me an editor so that I can copy / paste to keep the template the same)  and 2) create a subproject for me to edit in.

**Comment by nathandunn** [comment]
Conversely, I can create all of the doc locally as markdown in my repo and point to that maybe?  https://docs.gitbook.com/integrations/github   That's worth trying anyway.

**Comment by nathandunn** [comment]
Review:
- gitbook
- rtd
- gatsbyjs
- wordpress

**Comment by nathandunn** [comment]
https://github.com/ucscXena/xena-web

**Comment by nathandunn** [comment]
important features:
- some manner of search
- ability to embed images
- some way to monitor changes

**Comment by nathandunn** [comment]
https://docs.gitbook.com/integrations/github

**Comment by nathandunn** [comment]
I'm sure more will need to be done, but good enough for now.
