### ISSUE TITLE
expand color by type

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#233]
## Questions

--- 
Proposed coloring?:
- cnv >= 2 = red
- cnv <= -2 = blue
- mutation type 4 = red
- mutation type 3 = orange
- mutation type 2 = blue

---
- ~~Color by type only (as opposed to hit density)?~~ just treat single hit as max 

---
- ~~Horizontal split (have 3 and blue in both)?   Or don't split unless both are present?~~ keep cnv and mutation split)

**Comment by nathandunn** [comment]
FYI @jingchunzhu

**Comment by jingchunzhu** [comment]
> Color by type only (as opposed to hit density)?
Color (i.e. which color) by type, and the shade of the color (i.e. darker or lighter) by density. Currently we just have one color , the tealish color, right?

**Comment by nathandunn** [comment]
if mutations overlap, always take the highest mutation number

**Comment by nathandunn** [comment]
> - Color by type only (as opposed to hit density)?
   
Keep hit density

**Comment by nathandunn** [comment]
> - Horizontal split (have 3 and blue in both)? Or don't split unless both are present?

Keep split between CNV and mutation

**Comment by nathandunn** [comment]
Colors are chosen to match Xena.  

Can add a 3rd drop-down
