### ISSUE TITLE
more complete pathway list editor with multiple gene sets

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#27]

**Comment by nathandunn** [comment]
![Screen Shot 2018-05-31 at 1.59.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266457f26b7191a379f117224f5f565ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19041c95df44ce94d55a7143f6ae67e2431.png)

**Comment by nathandunn** [comment]
We will have 2400 gene sets so we either need:

1 - a gene set searcher / hub
2 - a way to catalog multiple sets of gene set searches

We would need to search by metadata such as scores, names, GO metadata, etc.

FYI @jingchunzhu

**Comment by nathandunn** [comment]
I think what is need to do is create a hub (not really that hard) and add metadata and allow it to be searchable in order to easily search, build them up and share.

**Comment by jingchunzhu** [comment]
How about the code just read a .json file with the 2400 pathway info into browser memory?

**Comment by nathandunn** [comment]
Local is fine, but we need to allow folks to jump between gene sets fairly easily as well as integrate within a tool, which is a fairly common use-case.  

Folks are going to want to look at PANCAN or different GO (or other ) pathways. 

That being said, generating JSON and feeding it into a tool like this is really easy to do, but we can definitely pre-load a larger set.


The harder problem is determining how to display > 30 gene sets.   A sortable / filterable shopping cart makes the most sense.   However, we need metadata of some sort to do this.  I think limiting to 30 (or some configurable number) views at a time makes the most sense.   We could even support pagination of these if it makes sense. 


Nathan

**Comment by jingchunzhu** [comment]
The current app has the functionality (or intent) of a user uploading a .json pathway file.  Isn't it easier to handle both sources of pathway information consistently? Why can't the app search the pathways within the javascript code, why does it have to rely on a server backend?

**Comment by nathandunn** [comment]
Another possibility to scrunch all of the genesets and sort . / filter by then. 

Ways to sort:
- A vs B difference
- min / max for A & B

Ways to filter:
- by gene(s) 
- min /max  scores

**Comment by nathandunn** [comment]
Already solved
