### ISSUE TITLE
upload of JSON must fails when removing selected gene set

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#306]
This fails during both the upload process as well as the editing process. 

Instead of failing this way it should select the first component and select that (or none).

**Comment by jingchunzhu** [comment]
In addition, after loading a new json file, the pathway background scoring colors do not show up until user manually refresh the app (e.g. using the chrome browser's refresh button).

**Comment by nathandunn** [comment]
fixed
