### ISSUE TITLE
handle multiple gene groups within a gene set

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#471]
Gene set will be grouped by positive versus negative genes and will be sorted here.

![image](https://user-images.githubusercontent.com/751274/69672418-eee89400-104c-11ea-83f6-58b1c8f68235.png)

**Comment by jingchunzhu** [comment]
[LUAD_577_regulons_20190509.txt.zip](https://github.com/ucscXena/XenaGoWidget/files/3894008/LUAD_577_regulons_20190509.txt.zip)

**Comment by jingchunzhu** [comment]
[convertR.py.zip](https://github.com/ucscXena/XenaGoWidget/files/3894014/convertR.py.zip)

**Comment by nathandunn** [comment]
will need to think about how to back-port this
