### ISSUE TITLE
correlate other data sets to go back into SS tool

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#567]
The idea would be to add the current activated view to the spreadsheet, including genesets and genes to allow users to further correlate. 

We would have to add extra hubs, etc. 

Potentially we could use sub-cohorts in some instances.  These might be in the spreadsheet.

**Comment by jingchunzhu** [comment]
doc on linking back to specific view in Xena 
https://ucsc-xena.gitbook.io/project/technical-documentation/deep-linking-into-xena

**Comment by nathandunn** [comment]
One column is all of the genes and the rest is the gene sets:

https://xenabrowser.net/heatmap/?columns=%5B%7B%22name%22%3A%22tcga_Kallisto_tpm%22%2C%22host%22%3A%22https%3A%2F%2Ftoil.xenahubs.net%22%2C%22fields%22%3A%22TP53%20FOXM1%22%7D%5D

**Comment by nathandunn** [comment]
Columns can have different hubs
