### ISSUE TITLE
fix dialog sizes

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#593]
- [ ] gene set dialog
- [ ] cohort editor

**Comment by jingchunzhu** [comment]
I noticed that the iframe dialog (see below) has the same problem. They are very wide. It is very easy for people to miss the 'close' button far away on the lower right corner. 
 
![image](https://user-images.githubusercontent.com/999493/84436419-4238c300-abe8-11ea-889e-fbcbcc68b01a.png)

**Comment by nathandunn** [comment]
Yeah, let me see what Brian suggests. 

Other libraries its an easy fix, but the dialogs here are pretty draconian. 

Nathan
