### ISSUE TITLE
update banner on pop-up

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/XenaGoWidget#597]
In looking at this with fresh eyes, I'm realizing it would be good to change the text on the banner from 'Differential Geneset Visualization' to 'Welcome to the Differential Geneset Visualization'. That way we help the user realize that they are entering a new tool.

**Comment by nathandunn** [comment]
I think we're still going to explore further integrations, so it **might** be more similar to a chart . . . we'll see.
