### ISSUE TITLE
UI styling

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/XenaGoWidget#599]
While the current UI uses Xena's fonts, the boxes and drop shadows are not UI elements currently in Xena. Perhaps we could use the cards from the material design we current use instead? Also, I see a faint gray box around everything but the banner. Remove unless there is something similar in our current UI elements that can be borrowed.

**Comment by nathandunn** [comment]
note . . related to #593 and #600

**Comment by nathandunn** [comment]
To use a card, we would have to be part of the component (as in #600).  Definitely a agree this is the approach we should take.
