### ISSUE TITLE
simplify Geneset configuration UI 

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/XenaGoWidget#608]
- [ ] add number limit and "most similar" vs "most differential" to visible controls
- [ ] remove "Find Gene"

---

Control edits:

- [ ] remove number limits
- [ ] add "find gene" to gene set filter (separate entry)
- [ ] sorting should be absolute diff (to pull) and then cohort diff (to view) -> same for CNV + Mutation, but the background is always the same

---

Unsure:
- [ ] provide a view for "most similar" or "must different" ??
- [ ] remove gene set editor link and popup??

**Comment by nathandunn** [comment]
@jingchunzhu 's use-cases:

- the numbers of pathways to display
- most differential and most similar pathways
- I want to see a set of pathways with certain names or genes
