### ISSUE TITLE
Improve UI 

### ISSUE THREAD

**Issue by 2580ayush2580** [ucscXena/XenaGoWidget#671]
I think we should add a spinner in loading section which helps user that the website is loading.

![u1](https://user-images.githubusercontent.com/56980422/103882145-64a0a980-5101-11eb-91c5-4d2d194322d7.png)

This is a demo example of loading spinner.

![u2](https://user-images.githubusercontent.com/56980422/103882427-ccef8b00-5101-11eb-8f24-9261e39d43ca.png)

**Comment by nathandunn** [comment]
@2580ayush2580  Are you suggesting that I add a spinning gif to what is currently there, or that I should obscure the whole screen with the gif? 

Thanks for the feedback.

**Comment by 2580ayush2580** [comment]
I am suggesting that we should add a spinner with what is currently there.

shall I work on this?

**Comment by nathandunn** [comment]
Yes, that would be very welcome. 

Thanks,

Nathan

**Comment by 2580ayush2580** [comment]
okay, I am working on this.
