### ISSUE TITLE
in the heatmap, explore possibility to use different color or shape to represent copy number gain, copy number loss, or mutation

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/XenaGoWidget#72]

**Comment by nathandunn** [comment]
<img width="988" alt="screen shot 2018-07-09 at 12 39 58 pm" src="https://user-images.githubusercontent.com/751274/42472489-4caf7d48-8376-11e8-9e40-9661f9161b24.png">

Though, we should probably synchronize on Xena's coloring.

**Comment by nathandunn** [comment]
Things to sort over:
- mutation and type
- copy number gain vs loss
