### ISSUE TITLE
sync color for genes and pathways

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/XenaGoWidget#78]
- [x] allow external configuration of the canvas color
- [x] configure genes to use a similar color schema
- [x] allow canvas to use min-vs-max 
min:[30,100,255],max:[180,255,0]
- [x] allow header to use min-vs-max as above
- [x] configure both to use min - vs - max
- [x] set pastel colors: https://color.adobe.com/explore/?filter=most-popular&time=month
   - [x] gene score
   - [x] pathway score
   - [ ] hover 
   - [x] select
   - [ ] menus, etc. 

From #71

**Comment by nathandunn** [comment]
Using: https://color.adobe.com/F%C3%B6delsedagskort-color-theme-10979072/?showPublished=true

Color: https://color.adobe.com/F%C3%B6delsedagskort-color-theme-10979072/?showPublished=true

- #E37B40
- #46B29D
- #DE5B49
- #324D5C
- #F0C94D

**Comment by nathandunn** [comment]
![Screen Shot 2018-07-20 at 5.07.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f36b7191a37df1122c4f5d5f5ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19141c95df549e04e57a6103f61e17e2431.png)

**Comment by nathandunn** [comment]
From Left to right:

- #E37B40 -> ignore (I think the menu can be purple, but will be over-written 
- #46B29D -> gene select
- #DE5B49 -> pathway select 
- #324D5C -> select 
- #F0C94D -> hover

====
![Screen Shot 2018-07-20 at 5.19.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f36b7191a37df113224f5b585ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19141c95df549e04e57a0133060e7772431.png)

**Comment by nathandunn** [comment]
![Screen Shot 2018-07-20 at 5.23.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f36b7191a37df110284f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ebc853b5922ce3e18abea841bee01ba21da1d87b3bd8e1ed2f42f67b6d5db1063474f4dcbed5727a19041c95df549e04e57a11a3062e4762431.png)

Using CMYK . . . .might be better?

**Comment by jingchunzhu** [comment]
So this is color for the User interface, like dropdown menu etc?

**Comment by nathandunn** [comment]
@jingchunzhu  These are the colors for the widget itself.   If you have better suggestions, let me know.   

The contrasts were pretty stark, so I'm trying to fix those.

**Comment by nathandunn** [comment]
Should use the rgba then for transparency.

**Comment by nathandunn** [comment]
I’ll assume that menus will be integrated into the xena client 

Nathan

**Comment by nathandunn** [comment]
Either way we can change the colors again later, but this should look much better

**Comment by nathandunn** [comment]
https://clevercanary.github.io/ucsc-cgl-style-guide/

**Comment by nathandunn** [comment]
Using clevercanary style-guide we have (note bug in guide for the select color in bottom-left):

From Left to right:

- [ ] TBD -> gene score , rgb(70,178,157), cmyk (61,0,12,30)
- [ ] TBD -> pathway score, , rgb(222,91,73), cmyk (0,59,67,13)
- [x] #113871 -> select 
- [x] #FFE66D -> hover

====
![screen shot 2018-07-23 at 9 58 14 am](https://user-images.githubusercontent.com/751274/43091602-5b65aea4-8e5f-11e8-9ad3-df1ea443273a.png)
